---
development:
  cloud_name: djzvesspw
  api_key: '922277323355664'
  api_secret: gbvQfzVRUbtjvRac4uKhlquo320
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: djzvesspw
  api_key: '922277323355664'
  api_secret: gbvQfzVRUbtjvRac4uKhlquo320
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: djzvesspw
  api_key: '922277323355664'
  api_secret: gbvQfzVRUbtjvRac4uKhlquo320
  enhance_image_tag: true
  static_image_support: false
